sudo: required
services:
  - docker

before_install:
  - docker build -t sohil2609/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sohil2609/react-test npm test -- --coverage

after_success:
  - docker build -t sohil2609/multi-client ./client
  - docker build -t sohil2609/multi-nginx ./nginx
  - docker build -t sohil2609/multi-worker ./worker
  - docker build -t sohil2609/multi-server ./server
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  - docker push sohil2609/multi-client
  - docker push sohil2609/multi-nginx
  - docker push sohil2609/multi-worker
  - docker push sohil2609/multi-server
