version: '3'
services:
  postgres-1:
    container_name: docker_postgres
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=password
  redis:
    container_name: docker_redis
    image: 'redis:latest'
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=docker_redis
      - REDIS_PORT=6379
      - PGHOST=docker_postgres
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=password
      - PGPORT=5432
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes: 
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=docker_redis
      - REDIS_PORT=6379
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8888:80'